---
steps:
  - label: ':debian: Build .deb file'
    command:
      - ./.buildkite/build-deb.sh
    artifact_paths: "build-bionic/*"

  - wait

  - label: ':postbox::debian: Sign and publish debs'
    command:
      - sign-debs build-bionic/*.deb
      - >
        aptly-upload
        --aptly-url https://apt-repo.kx.gd
        --retries 3
        --repo kx-builds-bionic
        --series bionic
        build-bionic/*.deb
    retry:
      automatic: true
    plugins:
      artifacts#v1.2.0:
        download: "build-bionic/*.deb"
      docker#v1.4.0:
        image: "${ECR}/ci-tools"
        always-pull: true
        workdir: /src
        environment:
          - APTLY_UNAME
          - APTLY_PASSWD
          - "GPG_KEY=${APT_GPG_KEY}"
